export const EVENT = {
    SET_BOARD_STATE: 'SET_BOARD_STATE',
    BOARD_RESIZE: 'BOARD_RESIZE',
    UPDATE_DATA: 'UPDATE_DATA',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    SHOW_NOTICE: 'SHOW_NOTICE',
    TOGGLE_GDRIVE_POPUP: 'TOGGLE_GDRIVE_POPUP',
    TOGGLE_FILE_BROWSER: 'TOGGLE_FILE_BROWSER',
    SET_CURRENT_ELEMENT: 'SET_CURRENT_ELEMENT'
};
